import { ScenarioConfig } from '../types/simulation';

export const SCENARIOS: ScenarioConfig[] = [
  {
    id: 'highway_cruise',
    name: 'High-Speed Highway Cruise',
    difficulty: 'Easy',
    description: '3-lane open expressway with moderate traffic flow. Tests efficient tactical overtaking and maintaining high cruising speed (28 m/s ~ 100 km/h) without unnecessary lane flapping.',
    speedLimit: 28.0,
    roadLength: 1200,
    spawnDensity: 14,
    initialEgoSpeed: 24.0,
    trafficTypes: ['car', 'truck'],
    hasObstacles: false,
    hasTrafficLights: false,
  },
  {
    id: 'dense_traffic',
    name: 'Dense Traffic & Gap Seeking',
    difficulty: 'Medium',
    description: 'Heavy bumper-to-bumper traffic in all lanes with variable speed dynamics. Agent must carefully identify safe inter-vehicle gaps for strategic lane changes.',
    speedLimit: 24.0,
    roadLength: 1000,
    spawnDensity: 28,
    initialEgoSpeed: 18.0,
    trafficTypes: ['car', 'truck', 'sport'],
    hasObstacles: false,
    hasTrafficLights: false,
  },
  {
    id: 'sudden_cut_in',
    name: 'Aggressive Cut-In & Hard Braking',
    difficulty: 'Hard',
    description: 'An aggressive sports vehicle from an adjacent lane cuts abruptly into the ego lane with rapid deceleration (-5 m/s²). Tests rapid emergency braking and situational awareness.',
    speedLimit: 26.0,
    roadLength: 900,
    spawnDensity: 16,
    initialEgoSpeed: 25.0,
    trafficTypes: ['car', 'sport'],
    hasObstacles: false,
    hasTrafficLights: false,
    specialEvent: 'cut_in',
  },
  {
    id: 'stalled_obstacle',
    name: 'Stationary Road Hazard & Forced Merge',
    difficulty: 'Hard',
    description: 'A stalled maintenance vehicle and warning barriers obstruct the ego lane 180m ahead. Agent must anticipate the obstruction, evaluate side mirrors, and smoothly merge.',
    speedLimit: 25.0,
    roadLength: 950,
    spawnDensity: 18,
    initialEgoSpeed: 22.0,
    trafficTypes: ['car', 'truck'],
    hasObstacles: true,
    hasTrafficLights: false,
    specialEvent: 'obstacle_block',
  },
  {
    id: 'stop_and_go',
    name: 'Stop-and-Go Traffic Shockwave',
    difficulty: 'Medium',
    description: 'A phantom traffic jam creates periodic speed oscillations from 22 m/s down to 4 m/s. Agent must dampen phantom waves and avoid rear-end collisions.',
    speedLimit: 22.0,
    roadLength: 1000,
    spawnDensity: 24,
    initialEgoSpeed: 19.0,
    trafficTypes: ['car', 'truck'],
    hasObstacles: false,
    hasTrafficLights: false,
    specialEvent: 'stop_and_go',
  },
  {
    id: 'traffic_intersection',
    name: 'Signalized Tactical Intersection',
    difficulty: 'Hard',
    description: 'Approaching an upcoming smart highway signal. The agent must balance stopping safely at red vs crossing legally on green, all while managing rear following buffers.',
    speedLimit: 20.0,
    roadLength: 800,
    spawnDensity: 12,
    initialEgoSpeed: 18.0,
    trafficTypes: ['car'],
    hasObstacles: false,
    hasTrafficLights: true,
  },
];
